services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: vercel_clone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vercel_clone_network

  upload-service:
    image: rohitshah1706/vercel_clone_upload_service:latest
    container_name: upload_service
    ports:
      - "5000:5000"
    env_file:
      - ./upload-service/.env
    volumes:
      - ./upload-service/data:/app/dist/clonedRepos
      - ./upload-service/kafka.pem:/app/kafka.pem
    networks:
      - vercel_clone_network

  deploy-service:
    image: rohitshah1706/vercel_clone_deploy_service:latest
    container_name: deploy_service
    env_file:
      - ./deploy-service/.env
    volumes:
      - ./deploy-service/data:/app/dist/clonedRepos
      - ./deploy-service/kafka.pem:/app/kafka.pem
    networks:
      - vercel_clone_network

  request-handler:
    image: rohitshah1706/vercel_clone_request_handler:latest
    container_name: request_handler
    ports:
      - "8080:8080"
    env_file:
      - ./request-handler/.env
    networks:
      - vercel_clone_network

  s3:
    image: localstack/localstack-s3-test:latest-s3
    container_name: localstack_s3
    ports:
      - "4566:4566"

  zookeeper:
    restart: always
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - vercel_clone_network

  kafka:
    restart: always
    image: bitnami/kafka:3.3
    container_name: kafka
    ports:
      - "9093:9093"
    volumes:
      - "kafka_volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - vercel_clone_network

networks:
  vercel_clone_network:
    driver: bridge

volumes:
  kafka_volume:
  zookeeper_volume:
  postgres_data:
