import {getServerSession} from "next-auth";
import SessionProvider from "./_components/SessionProvider";
import NavMenu from "./_components/NavMenu";

import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// ! since this is treated as a server component we can't use React Context
// ! so we need to use the SessionProvider from next-auth/react to provide session data to all client-side components
export default async function RootLayout({children}) {
	const session = await getServerSession();

	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionProvider session={session}>
					<main className="mx-auto max-w-5xl text-2xl flex gap-2">
						<NavMenu />
						{children}
					</main>
				</SessionProvider>
			</body>
		</html>
	);
}
