import dotenv from "dotenv";
dotenv.config();

const AWS_S3_BUCKET_NAME = process.env.AWS_S3_BUCKET_NAME || "";
const AWS_S3_BUCKET_REGION = process.env.AWS_S3_BUCKET_REGION || "";
const AWS_EXPRESSAPP_USER_ACCESS_KEY =
	process.env.AWS_EXPRESSAPP_USER_ACCESS_KEY || "";
const AWS_EXPRESSAPP_USER_SECRET_ACCESS_KEY =
	process.env.AWS_EXPRESSAPP_USER_SECRET_ACCESS_KEY || "";

export {
	AWS_S3_BUCKET_NAME,
	AWS_S3_BUCKET_REGION,
	AWS_EXPRESSAPP_USER_ACCESS_KEY,
	AWS_EXPRESSAPP_USER_SECRET_ACCESS_KEY,
};
